controller_manager:
  ros__parameters:
    update_rate: 30  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    forward_velocity_controller:
      type: forward_command_controller/ForwardCommandController

forward_position_controller:
  ros__parameters:
    joints:
      - RightBackSupport
      - RightFrontSupport
      - LeftFrontSupport
      - LeftBackSupport
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

forward_velocity_controller:
  ros__parameters:
    joints:
      - RightBack_wheel
      - RightFront_wheel
      - RightMid_wheel
      - LeftFront_wheel
      - LeftBack_wheel
      - LeftMid_wheel
    interface_name: velocity
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
